import { Icon } from '@/components/icon';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { projects } from '@/data/portfolio';
import { ProjectMedia } from '@/components/project-media';
import { MediaBlock } from '@/components/case-study';
export function generateStaticParams() { return projects.map(p => ({ slug: p.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const project = projects.find(p => p.slug === slug); return { title: project?.title || 'Project not found', description: project?.subtitle }; }
export default async function ProjectPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const index = projects.findIndex(p => p.slug === slug); if (index < 0) notFound(); const p = projects[index]; const next = projects[(index + 1) % projects.length]; return <main id="main" className="wrap case-page"><Link className="back-link mono" href="/work"><Icon name="arrow-left" /> BACK TO WORK</Link><h1 className="case-title">{p.title}</h1><p className="case-subtitle">{p.subtitle}</p><dl className="case-meta">{Object.entries({ Role: p.role, Timeline: p.timeline, Platform: p.platform, Year: p.year }).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><ProjectMedia title={p.title} color={p.color} src={p.heroImage} /><p className="case-status mono">CASE STUDY IN PROGRESS · CONTENT AND VISUALS ARE EDITABLE PLACEHOLDERS</p>{p.sections.map((section, i) => <section className="case-section" key={section.title}><h2><span className="mono">0{i + 1}</span>{section.title}</h2><div className="case-blocks">{section.blocks.map((block, j) => <MediaBlock key={j} block={block} />)}</div></section>)}<nav className="project-navigation" aria-label="More projects"><span className="mono muted">NEXT PROJECT</span><Link href={`/work/${next.slug}`}>{next.title} <Icon name="arrow-up-right" /></Link></nav></main>; }
